import fs from 'fs';
import path from 'path';

const storePath = path.resolve('src/lib/store.ts');
let content = fs.readFileSync(storePath, 'utf8');

const brandsAndProducts = `export const INITIAL_BRANDS: Brand[] = [
  { id: "br-1", name: "Mahadhan", manufacturer: "Deepak Fertilisers & Petrochemicals", isDemo: true },
  { id: "br-2", name: "Yara India", manufacturer: "Yara International", isDemo: true },
  { id: "br-3", name: "Bayer CropScience", manufacturer: "Bayer AG", isDemo: true },
  { id: "br-4", name: "Syngenta India", manufacturer: "Syngenta Group", isDemo: true },
  { id: "br-5", name: "UPL Limited", manufacturer: "UPL Ltd", isDemo: true },
  { id: "br-6", name: "Dhanuka Agritech", manufacturer: "Dhanuka", isDemo: true },
  { id: "br-7", name: "Sumitomo Chemical", manufacturer: "Sumitomo", isDemo: true },
  { id: "br-8", name: "Advanta Seeds", manufacturer: "Advanta Enterprise", isDemo: true },
  { id: "br-9", name: "Multiplex", manufacturer: "Multiplex Group", isDemo: true },
  { id: "br-10", name: "Corteva Agriscience", manufacturer: "Corteva Inc", isDemo: true },
  { id: "br-11", name: "IFFCO", manufacturer: "Indian Farmers Fertiliser Cooperative", isDemo: true },
  { id: "br-12", name: "Coromandel", manufacturer: "Coromandel International Ltd", isDemo: true },
  { id: "br-13", name: "Tata Rallis", manufacturer: "Rallis India (Tata)", isDemo: true },
  { id: "br-14", name: "Godrej Agrovet", manufacturer: "Godrej Group", isDemo: true },
  { id: "br-15", name: "Panchganga Seeds", manufacturer: "Panchganga Seeds Pvt Ltd", isDemo: true },
  { id: "br-16", name: "Pioneer Seeds", manufacturer: "Corteva Pioneer", isDemo: true },
];

export const INITIAL_PRODUCTS: Product[] = [
  // ==========================================
  // १. खते व विद्राव्य खते (Fertilizers & WSF)
  // ==========================================
  {
    id: "prod-1",
    nameEn: "Mahadhan 19:19:19 (Starter Grade)",
    nameMr: "महाधन १९:१९:१९ (विद्राव्य खत)",
    brandId: "br-1",
    brandName: "Mahadhan",
    categoryId: "cat-1",
    categoryNameEn: "Water Soluble Fertilizers",
    categoryNameMr: "विद्राव्य खते",
    sku: "MDH-191919-1KG",
    hsnCode: "31052000",
    unit: "Kg",
    packSize: "1 Kg Bag",
    mrp: 220,
    sellingPrice: 190,
    purchasePrice: 155,
    gstRate: 5,
    totalStock: 85,
    minStockLevel: 20,
    isAvailable: true,
    technicalName: "NPK 19:19:19 100% Water Soluble",
    targetCrops: "कांदा, द्राक्ष, डाळिंब, टोमॅटो, भाजीपाला",
    dosageGuide: "५ ग्रॅम प्रति लिटर पाणी फवारणी किंवा ३-५ किलो प्रति एकर ठिबकद्वारे",
    descriptionEn: "Balanced NPK for rapid early vegetative growth and root development.",
    descriptionMr: "सुरुवातीच्या शाखीय वाढीसाठी व मुळांच्या मजबुतीसाठी १००% विद्राव्य खत.",
    batches: [
      {
        id: "batch-1a",
        productId: "prod-1",
        batchNumber: "MDH-24-A01",
        mfgDate: "2024-05-10",
        expiryDate: "2027-05-09",
        purchaseCost: 155,
        currentStock: 85,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-2",
    nameEn: "Mahadhan 0:52:34 (MKP Flower & Bulb Grade)",
    nameMr: "महाधन ०:५२:३४ (मोनो पोटॅशियम फॉस्फेट)",
    brandId: "br-1",
    brandName: "Mahadhan",
    categoryId: "cat-1",
    categoryNameEn: "Water Soluble Fertilizers",
    categoryNameMr: "विद्राव्य खते",
    sku: "MDH-05234-1KG",
    hsnCode: "31052000",
    unit: "Kg",
    packSize: "1 Kg Bag",
    mrp: 250,
    sellingPrice: 210,
    purchasePrice: 175,
    gstRate: 5,
    totalStock: 60,
    minStockLevel: 15,
    isAvailable: true,
    technicalName: "Monopotassium Phosphate (00:52:34)",
    targetCrops: "कांदा गाठ फुगवण, द्राक्ष घड विकास, टोमॅटो, डाळिंब",
    dosageGuide: "५-७ ग्रॅम प्रति लिटर पाणी फवारणी किंवा ४-५ किलो प्रति एकर",
    descriptionEn: "High phosphorus and potash for heavy flowering and bulb formation.",
    descriptionMr: "कांदा गाठ फुगवणीसाठी आणि फळांच्या व कळ्यांच्या योग्य विकासासाठी उत्कृष्ट.",
    batches: [
      {
        id: "batch-2a",
        productId: "prod-2",
        batchNumber: "MDH-24-B109",
        mfgDate: "2024-06-01",
        expiryDate: "2027-05-31",
        purchaseCost: 175,
        currentStock: 60,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-3",
    nameEn: "Mahadhan 12:61:00 (MAP Root Booster)",
    nameMr: "महाधन १२:६१:०० (मोनो अमोनियम फॉस्फेट)",
    brandId: "br-1",
    brandName: "Mahadhan",
    categoryId: "cat-1",
    categoryNameEn: "Water Soluble Fertilizers",
    categoryNameMr: "विद्राव्य खते",
    sku: "MDH-126100-1KG",
    hsnCode: "31052000",
    unit: "Kg",
    packSize: "1 Kg Bag",
    mrp: 270,
    sellingPrice: 240,
    purchasePrice: 195,
    gstRate: 5,
    totalStock: 45,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Mono Ammonium Phosphate (12:61:00)",
    targetCrops: "कांदा रोपवाटिका, टोमॅटो लागवड, द्राक्ष, डाळिंब",
    dosageGuide: "५ ग्रॅम प्रति लिटर पाणी फवारणी किंवा ३-५ किलो प्रति एकर ठिबक",
    descriptionEn: "High phosphorus fertilizer for vigorous root establishment and early growth.",
    descriptionMr: "मुळांची भरपूर वाढ आणि जोमदार फुटवे येण्यासाठी लागवडीच्या सुरुवातीचे सर्वोत्तम खत.",
    batches: [
      {
        id: "batch-3a",
        productId: "prod-3",
        batchNumber: "MDH-24-MAP",
        mfgDate: "2024-04-12",
        expiryDate: "2027-04-11",
        purchaseCost: 195,
        currentStock: 45,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-4",
    nameEn: "Mahadhan 0:0:50 (SOP Potassium Sulphate)",
    nameMr: "महाधन ०:०:५० (पोटॅशियम सल्फेट विद्राव्य)",
    brandId: "br-1",
    brandName: "Mahadhan",
    categoryId: "cat-1",
    categoryNameEn: "Water Soluble Fertilizers",
    categoryNameMr: "विद्राव्य खते",
    sku: "MDH-0050-1KG",
    hsnCode: "31052000",
    unit: "Kg",
    packSize: "1 Kg Bag",
    mrp: 210,
    sellingPrice: 180,
    purchasePrice: 145,
    gstRate: 5,
    totalStock: 50,
    minStockLevel: 15,
    isAvailable: true,
    technicalName: "Sulphate of Potash (0:0:50 + 17.5% Sulphur)",
    targetCrops: "कांदा (पक्वता), द्राक्ष (साखर व चकाकी), डाळिंब रंग, टोमॅटो",
    dosageGuide: "५-६ ग्रॅम प्रति लिटर पाणी किंवा ५ किलो प्रति एकर ठिबक",
    descriptionEn: "Improves fruit weight, luster, sugar content and increases shelf life.",
    descriptionMr: "फळांचे वजन, चकाकी, साखर वाढवणे व कांद्याची टिकवण क्षमता वाढवण्यासाठी.",
    batches: [
      {
        id: "batch-4a",
        productId: "prod-4",
        batchNumber: "MDH-24-SOP",
        mfgDate: "2024-05-15",
        expiryDate: "2027-05-14",
        purchaseCost: 145,
        currentStock: 50,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-5",
    nameEn: "YaraLiva Nitrabor (Calcium Nitrate + Boron)",
    nameMr: "यारालिवा नायट्राबोर (कॅल्शियम नायट्रेट + बोरॉन)",
    brandId: "br-2",
    brandName: "Yara India",
    categoryId: "cat-6",
    categoryNameEn: "Micronutrients & Secondary Nutrients",
    categoryNameMr: "सूक्ष्म अन्नद्रव्ये",
    sku: "YARA-NITRA-25KG",
    hsnCode: "31026000",
    unit: "Bag",
    packSize: "25 Kg Bag",
    mrp: 2150,
    sellingPrice: 1950,
    purchasePrice: 1680,
    gstRate: 5,
    totalStock: 28,
    minStockLevel: 8,
    isAvailable: true,
    technicalName: "Calcium Nitrate with 0.3% Boron",
    targetCrops: "द्राक्ष, डाळिंब (फळ तडकणे रोखण्यासाठी), टोमॅटो, कांदा",
    dosageGuide: "१०-१५ किलो प्रति एकर ठिबकद्वारे किंवा जमिनीतून",
    descriptionEn: "Premium soluble calcium and boron to prevent fruit cracking and improve storage life.",
    descriptionMr: "फळे तडकणे थांबवण्यासाठी, चमक आणण्यासाठी व कांद्याची टिकवण क्षमता वाढवण्यासाठी.",
    batches: [
      {
        id: "batch-5a",
        productId: "prod-5",
        batchNumber: "YAR-24-992",
        mfgDate: "2024-03-15",
        expiryDate: "2027-03-14",
        purchaseCost: 1680,
        currentStock: 28,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-6",
    nameEn: "IFFCO Neem Coated Urea",
    nameMr: "इफ्को नीम कोटेड युरिया (Urea 46% N)",
    brandId: "br-11",
    brandName: "IFFCO",
    categoryId: "cat-2",
    categoryNameEn: "Chemical & Organic Fertilizers",
    categoryNameMr: "रासायनिक खते",
    sku: "IFF-UREA-45KG",
    hsnCode: "31021000",
    unit: "Bag",
    packSize: "45 Kg Bag",
    mrp: 266,
    sellingPrice: 266,
    purchasePrice: 242,
    gstRate: 5,
    totalStock: 120,
    minStockLevel: 30,
    isAvailable: true,
    technicalName: "Neem Coated Urea (46% Nitrogen)",
    targetCrops: "सर्व पिके, कांदा, मका, गहू, ऊस",
    dosageGuide: "४५-९० किलो प्रति एकर जमिनीतून",
    descriptionEn: "Government subsidized primary nitrogen fertilizer for vegetative growth.",
    descriptionMr: "पिकांच्या जोमदार वाढीसाठी प्राथमिक नत्र खत.",
    batches: [
      {
        id: "batch-6a",
        productId: "prod-6",
        batchNumber: "IFF-UR-88",
        mfgDate: "2024-06-01",
        expiryDate: "2027-05-31",
        purchaseCost: 242,
        currentStock: 120,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-7",
    nameEn: "IFFCO DAP (Di-Ammonium Phosphate 18:46:0)",
    nameMr: "इफ्को डीएपी (डीएपी १८:४६:० खत)",
    brandId: "br-11",
    brandName: "IFFCO",
    categoryId: "cat-2",
    categoryNameEn: "Chemical & Organic Fertilizers",
    categoryNameMr: "रासायनिक खते",
    sku: "IFF-DAP-50KG",
    hsnCode: "31053000",
    unit: "Bag",
    packSize: "50 Kg Bag",
    mrp: 1350,
    sellingPrice: 1350,
    purchasePrice: 1260,
    gstRate: 5,
    totalStock: 80,
    minStockLevel: 25,
    isAvailable: true,
    technicalName: "Di-Ammonium Phosphate (18% N + 46% P2O5)",
    targetCrops: "कांदा लागवड, मका, सोयाबीन, भाजीपाला बेसल डोस",
    dosageGuide: "५०-१०० किलो प्रति एकर बेसल डोस म्हणून",
    descriptionEn: "Essential basal fertilizer supplying high concentration of phosphate and nitrogen.",
    descriptionMr: "लागवडीच्या वेळी जमिनीतून देण्याचे मुख्य स्फुरद व नत्रयुक्त खत.",
    batches: [
      {
        id: "batch-7a",
        productId: "prod-7",
        batchNumber: "IFF-DAP-41",
        mfgDate: "2024-05-20",
        expiryDate: "2027-05-19",
        purchaseCost: 1260,
        currentStock: 80,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-8",
    nameEn: "Mahadhan 10:26:26 Mahapower Complex",
    nameMr: "महाधन १०:२६:२६ (महापावर खत)",
    brandId: "br-1",
    brandName: "Mahadhan",
    categoryId: "cat-2",
    categoryNameEn: "Chemical & Organic Fertilizers",
    categoryNameMr: "रासायनिक खते",
    sku: "MDH-102626-50KG",
    hsnCode: "31052000",
    unit: "Bag",
    packSize: "50 Kg Bag",
    mrp: 1520,
    sellingPrice: 1470,
    purchasePrice: 1340,
    gstRate: 5,
    totalStock: 65,
    minStockLevel: 20,
    isAvailable: true,
    technicalName: "NPK Complex (10% N + 26% P2O5 + 26% K2O)",
    targetCrops: "कांदा, द्राक्ष, डाळिंब, भाजीपाला",
    dosageGuide: "५०-१०० किलो प्रति एकर",
    descriptionEn: "Balanced high-potash and phosphorus complex fertilizer for tuber and fruit crops.",
    descriptionMr: "कांदा व फळबागांसाठी स्फुरद व पालाशयुक्त आदर्श संयुक्त खत.",
    batches: [
      {
        id: "batch-8a",
        productId: "prod-8",
        batchNumber: "MDH-1026-9",
        mfgDate: "2024-06-10",
        expiryDate: "2027-06-09",
        purchaseCost: 1340,
        currentStock: 65,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },

  // ==========================================
  // २. फवारणीची बुरशीनाशके (Fungicides)
  // ==========================================
  {
    id: "prod-9",
    nameEn: "Bayer Nativo (Tebuconazole + Trifloxystrobin)",
    nameMr: "बायर नॅटिव्हो बुरशीनाशक (करपा व भुरी नियंत्रक)",
    brandId: "br-3",
    brandName: "Bayer CropScience",
    categoryId: "cat-3",
    categoryNameEn: "Fungicides",
    categoryNameMr: "बुरशीनाशके",
    sku: "BAY-NAT-100G",
    hsnCode: "38089290",
    unit: "Bottle",
    packSize: "100 Gm",
    mrp: 850,
    sellingPrice: 760,
    purchasePrice: 620,
    gstRate: 18,
    totalStock: 45,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Tebuconazole 50% + Trifloxystrobin 25% WG",
    targetCrops: "कांदा (जांभळा करपा), द्राक्ष (भुरी/डावणी), टोमॅटो, डाळिंब",
    dosageGuide: "०.५ ग्रॅम प्रति लिटर पाणी (१०० ग्रॅम प्रति २०० लिटर पाणी)",
    descriptionEn: "Dual systemic broad spectrum fungicide with excellent curative and protective power.",
    descriptionMr: "कांदा जांभळा करपा आणि द्राक्ष बागेतील भुरी रोगावर अत्यंत प्रभावी आंतरप्रवाही बुरशीनाशक.",
    batches: [
      {
        id: "batch-9a",
        productId: "prod-9",
        batchNumber: "BY-NAT-771",
        mfgDate: "2024-04-10",
        expiryDate: "2026-09-20",
        purchaseCost: 620,
        currentStock: 45,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-10",
    nameEn: "Syngenta Amistar Top",
    nameMr: "सिंजेन्टा ॲमिस्टार टॉप (उत्कृष्ट बुरशीनाशक)",
    brandId: "br-4",
    brandName: "Syngenta India",
    categoryId: "cat-3",
    categoryNameEn: "Fungicides",
    categoryNameMr: "बुरशीनाशके",
    sku: "SYN-AMIS-200ML",
    hsnCode: "38089290",
    unit: "Bottle",
    packSize: "200 ml",
    mrp: 920,
    sellingPrice: 780,
    purchasePrice: 650,
    gstRate: 18,
    totalStock: 38,
    minStockLevel: 8,
    isAvailable: true,
    technicalName: "Azoxystrobin 18.2% + Difenoconazole 11.4% SC",
    targetCrops: "कांदा (करपा), द्राक्ष, डाळिंब (अँथ्रॅकनोज/डाग), टोमॅटो",
    dosageGuide: "१ मिली प्रति लिटर पाणी (२०० मिली प्रति २०० लिटर पाणी)",
    descriptionEn: "Broad spectrum fungicide that promotes greening effect and shields against severe blights.",
    descriptionMr: "कांदा पीक टवटवीत व हिरवेगार ठेवून करप्यापासून संपूर्ण संरक्षण देणारे सर्वोत्तम औषध.",
    batches: [
      {
        id: "batch-10a",
        productId: "prod-10",
        batchNumber: "SYN-AMT-441",
        mfgDate: "2024-02-18",
        expiryDate: "2026-11-10",
        purchaseCost: 650,
        currentStock: 38,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-11",
    nameEn: "Syngenta Ridomil Gold",
    nameMr: "सिंजेन्टा रिडोमिल गोल्ड (डावणी व करपा नियंत्रक)",
    brandId: "br-4",
    brandName: "Syngenta India",
    categoryId: "cat-3",
    categoryNameEn: "Fungicides",
    categoryNameMr: "बुरशीनाशके",
    sku: "SYN-RID-500G",
    hsnCode: "38089290",
    unit: "Packet",
    packSize: "500 Gm",
    mrp: 1350,
    sellingPrice: 1150,
    purchasePrice: 960,
    gstRate: 18,
    totalStock: 25,
    minStockLevel: 6,
    isAvailable: true,
    technicalName: "Metalaxyl-M 4% + Mancozeb 64% WP",
    targetCrops: "द्राक्ष (डावणी/Downy Mildew), कांदा, टोमॅटो लेट ब्लाइट",
    dosageGuide: "२.५ ग्रॅम प्रति लिटर पाणी",
    descriptionEn: "World benchmark systemic fungicide against downy mildew and damping off.",
    descriptionMr: "द्राक्षातील डावणी आणि कांद्यातील करप्यावर जागतिक दर्जाचे खात्रीशीर औषध.",
    batches: [
      {
        id: "batch-11a",
        productId: "prod-11",
        batchNumber: "SYN-RD-12",
        mfgDate: "2024-03-01",
        expiryDate: "2026-12-31",
        purchaseCost: 960,
        currentStock: 25,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-12",
    nameEn: "UPL Saaf Fungicide",
    nameMr: "युपीएल साफ बुरशीनाशक (Carbendazim + Mancozeb)",
    brandId: "br-5",
    brandName: "UPL Limited",
    categoryId: "cat-3",
    categoryNameEn: "Fungicides",
    categoryNameMr: "बुरशीनाशके",
    sku: "UPL-SAAF-500G",
    hsnCode: "38089290",
    unit: "Packet",
    packSize: "500 Gm",
    mrp: 420,
    sellingPrice: 360,
    purchasePrice: 285,
    gstRate: 18,
    totalStock: 60,
    minStockLevel: 15,
    isAvailable: true,
    technicalName: "Carbendazim 12% + Mancozeb 63% WP",
    targetCrops: "कांदा, शेंगदाणा, टोमॅटो, मिरची, भाजीपाला, बीजप्रक्रिया",
    dosageGuide: "२ ग्रॅम प्रति लिटर पाणी किंवा २ ग्रॅम प्रति किलो बियाणे",
    descriptionEn: "Cost-effective contact and systemic fungicide for multiple fungal blights.",
    descriptionMr: "करपा, तांबेरा व मूळकूज नियंत्रणासाठी शेतकऱ्यांचे अत्यंत लोकप्रिय औषध.",
    batches: [
      {
        id: "batch-12a",
        productId: "prod-12",
        batchNumber: "UPL-SF-90",
        mfgDate: "2024-05-01",
        expiryDate: "2027-04-30",
        purchaseCost: 285,
        currentStock: 60,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },

  // ==========================================
  // ३. फवारणीची कीटकनाशके (Insecticides)
  // ==========================================
  {
    id: "prod-14",
    nameEn: "FMC Coragen (Chlorantraniliprole 18.5% SC)",
    nameMr: "एफएमसी कोराजन (अळी व कीटक नियंत्रक)",
    brandId: "br-4",
    brandName: "Syngenta India",
    categoryId: "cat-4",
    categoryNameEn: "Insecticides",
    categoryNameMr: "कीटकनाशके",
    sku: "COR-60ML",
    hsnCode: "38089190",
    unit: "Bottle",
    packSize: "60 ml",
    mrp: 1050,
    sellingPrice: 940,
    purchasePrice: 780,
    gstRate: 18,
    totalStock: 22,
    minStockLevel: 8,
    isAvailable: true,
    technicalName: "Chlorantraniliprole 18.5% SC (Rynaxypyr)",
    targetCrops: "टोमॅटो फळपोखरणाऱ्या अळ्या, मका लष्करी अळी, कांदा, सोयाबीन",
    dosageGuide: "०.३ मिली प्रति लिटर पाणी (६० मिली प्रति एकर फवारणी)",
    descriptionEn: "Long lasting systemic control against caterpillar pests, borers and armyworms.",
    descriptionMr: "अळी, फळपोखरणारी कीड व लष्करी अळीवर २१ दिवसांपर्यंत दीर्घकाळ संरक्षण देणारे औषध.",
    batches: [
      {
        id: "batch-14a",
        productId: "prod-14",
        batchNumber: "CRG-24-09",
        mfgDate: "2024-01-11",
        expiryDate: "2027-01-10",
        purchaseCost: 780,
        currentStock: 22,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-15",
    nameEn: "Corteva Delegate (Spinetoram 11.7% SC)",
    nameMr: "कॉर्टेव्हा डेलिगेट (थ्रिप्स व अळी नाशक)",
    brandId: "br-10",
    brandName: "Corteva Agriscience",
    categoryId: "cat-4",
    categoryNameEn: "Insecticides",
    categoryNameMr: "कीटकनाशके",
    sku: "COR-DEL-100ML",
    hsnCode: "38089190",
    unit: "Bottle",
    packSize: "100 ml",
    mrp: 1650,
    sellingPrice: 1450,
    purchasePrice: 1220,
    gstRate: 18,
    totalStock: 18,
    minStockLevel: 5,
    isAvailable: true,
    technicalName: "Spinetoram 11.7% SC",
    targetCrops: "कांदा थ्रिप्स (Onion Thrips), मिरची, टोमॅटो, कापूस",
    dosageGuide: "०.९ मिली प्रति लिटर पाणी (१८० मिली प्रति एकर)",
    descriptionEn: "Next generation spinosyn insecticide with rapid knockdown and ovicidal action against thrips.",
    descriptionMr: "कांद्यातील हट्टी थ्रिप्स (बोकड्या) व अळ्यांवर तात्काळ परिणाम करणारे आधुनिक कीटकनाशक.",
    batches: [
      {
        id: "batch-15a",
        productId: "prod-15",
        batchNumber: "DEL-24-11",
        mfgDate: "2024-03-20",
        expiryDate: "2026-10-15",
        purchaseCost: 1220,
        currentStock: 18,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-16",
    nameEn: "Syngenta Alika",
    nameMr: "सिंजेन्टा अलिका (मावा, तुडतुडे व अळी नाशक)",
    brandId: "br-4",
    brandName: "Syngenta India",
    categoryId: "cat-4",
    categoryNameEn: "Insecticides",
    categoryNameMr: "कीटकनाशके",
    sku: "SYN-ALK-100ML",
    hsnCode: "38089190",
    unit: "Bottle",
    packSize: "100 ml",
    mrp: 440,
    sellingPrice: 390,
    purchasePrice: 310,
    gstRate: 18,
    totalStock: 40,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Thiamethoxam 12.6% + Lambda-Cyhalothrin 9.5% ZC",
    targetCrops: "कांदा, टोमॅटो, भाजीपाला, मका, सोयाबीन",
    dosageGuide: "०.५ मिली प्रति लिटर पाणी (८० मिली प्रति एकर)",
    descriptionEn: "Combination insecticide offering systemic and contact knock-down against sucking and chewing pests.",
    descriptionMr: "रसशोषक किडी (मावा, तुडतुडे, पांढरी माशी) व अळीवर एकाच वेळी दुहेरी मारा करणारे औषध.",
    batches: [
      {
        id: "batch-16a",
        productId: "prod-16",
        batchNumber: "ALK-24-88",
        mfgDate: "2024-04-05",
        expiryDate: "2027-04-04",
        purchaseCost: 310,
        currentStock: 40,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-17",
    nameEn: "Bayer Confidor (Imidacloprid 17.8% SL)",
    nameMr: "बायर कॉनफिडोर (रसशोषक कीड नियंत्रक)",
    brandId: "br-3",
    brandName: "Bayer CropScience",
    categoryId: "cat-4",
    categoryNameEn: "Insecticides",
    categoryNameMr: "कीटकनाशके",
    sku: "BAY-CONF-100ML",
    hsnCode: "38089190",
    unit: "Bottle",
    packSize: "100 ml",
    mrp: 430,
    sellingPrice: 380,
    purchasePrice: 295,
    gstRate: 18,
    totalStock: 35,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Imidacloprid 17.8% SL",
    targetCrops: "कांदा, मिरची, टोमॅटो, द्राक्ष, कापूस",
    dosageGuide: "०.५ मिली प्रति लिटर पाणी",
    descriptionEn: "Systemic neonicotinoid insecticide for sucking pests with translaminar activity.",
    descriptionMr: "मावा, तुडतुडे, फुलकिडे व पांढऱ्या माशीवर रामबाण आंतरप्रवाही औषध.",
    batches: [
      {
        id: "batch-17a",
        productId: "prod-17",
        batchNumber: "CNF-24-3",
        mfgDate: "2024-05-10",
        expiryDate: "2027-05-09",
        purchaseCost: 295,
        currentStock: 35,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-18",
    nameEn: "Bayer Jump (Fipronil 80% WG)",
    nameMr: "बायर जम्प (कांदा थ्रिप्स स्पेशल Fipronil)",
    brandId: "br-3",
    brandName: "Bayer CropScience",
    categoryId: "cat-4",
    categoryNameEn: "Insecticides",
    categoryNameMr: "कीटकनाशके",
    sku: "BAY-JUMP-40G",
    hsnCode: "38089190",
    unit: "Bottle",
    packSize: "40 Gm",
    mrp: 390,
    sellingPrice: 340,
    purchasePrice: 275,
    gstRate: 18,
    totalStock: 30,
    minStockLevel: 8,
    isAvailable: true,
    technicalName: "Fipronil 80% WG",
    targetCrops: "कांदा (थ्रिप्स/बोकड्या), द्राक्ष, भात, मिरची",
    dosageGuide: "०.३ ग्रॅम प्रति लिटर पाणी (४० ग्रॅम प्रति १००-१५० लिटर पाणी)",
    descriptionEn: "High-concentration fipronil with plant growth enhancement and thrips eradication.",
    descriptionMr: "कांद्यातील थ्रिप्सचे समूळ उच्चाटन करून पानांना हिरवेगार बनवणारे औषध.",
    batches: [
      {
        id: "batch-18a",
        productId: "prod-18",
        batchNumber: "JMP-24-02",
        mfgDate: "2024-04-12",
        expiryDate: "2027-04-11",
        purchaseCost: 275,
        currentStock: 30,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },

  // ==========================================
  // ४. टॉनिक, संजीवके व स्टीकर (Tonics & Spreaders)
  // ==========================================
  {
    id: "prod-19",
    nameEn: "Syngenta Isabion Amino Acids Tonic",
    nameMr: "सिंजेन्टा इसाबियन (अमिनो ॲसिड टॉनिक)",
    brandId: "br-4",
    brandName: "Syngenta India",
    categoryId: "cat-7",
    categoryNameEn: "Plant Growth Regulators & Tonics",
    categoryNameMr: "टॉनिक व पीजीआर",
    sku: "SYN-ISA-500ML",
    hsnCode: "38089340",
    unit: "Bottle",
    packSize: "500 ml",
    mrp: 560,
    sellingPrice: 480,
    purchasePrice: 380,
    gstRate: 12,
    totalStock: 40,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Amino Acids 62.5% + Peptides Nutrient Activator",
    targetCrops: "कांदा, द्राक्ष, डाळिंब, टोमॅटो, फुलपिके, भाजीपाला",
    dosageGuide: "२ मिली प्रति लिटर पाणी (४००-५०० मिली प्रति एकर फवारणी)",
    descriptionEn: "Biostimulant that enhances flower set, reduces fruit drop and improves plant vitality.",
    descriptionMr: "फुलधारणा वाढवण्यासाठी, पिकाची ताकद वाढवण्यासाठी व फळांची चमकदार वाढ होण्यासाठीचे सेंद्रिय टॉनिक.",
    batches: [
      {
        id: "batch-19a",
        productId: "prod-19",
        batchNumber: "ISA-24-51",
        mfgDate: "2024-05-18",
        expiryDate: "2027-05-17",
        purchaseCost: 380,
        currentStock: 40,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-20",
    nameEn: "Godrej Double Homobrassinolide Tonic",
    nameMr: "गोदरेज डबल टॉनिक (Homobrassinolide 0.04%)",
    brandId: "br-14",
    brandName: "Godrej Agrovet",
    categoryId: "cat-7",
    categoryNameEn: "Plant Growth Regulators & Tonics",
    categoryNameMr: "टॉनिक व पीजीआर",
    sku: "GDJ-DBL-250ML",
    hsnCode: "38089340",
    unit: "Bottle",
    packSize: "250 ml",
    mrp: 370,
    sellingPrice: 320,
    purchasePrice: 245,
    gstRate: 12,
    totalStock: 30,
    minStockLevel: 8,
    isAvailable: true,
    technicalName: "Homobrassinolide 0.04% EC",
    targetCrops: "कांदा (फुगवण), द्राक्ष (मणी फुगवण), डाळिंब, टोमॅटो",
    dosageGuide: "०.५ मिली प्रति लिटर पाणी (१०० मिली प्रति एकर)",
    descriptionEn: "Potent brassinosteroid growth promoter for cell elongation and bulb weight boost.",
    descriptionMr: "कांदा गाठ फुगवण्यासाठी व द्राक्ष मण्यांची फुगवण वाढवणारे शास्त्रीय टॉनिक.",
    batches: [
      {
        id: "batch-20a",
        productId: "prod-20",
        batchNumber: "DBL-24-04",
        mfgDate: "2024-04-22",
        expiryDate: "2027-04-21",
        purchaseCost: 245,
        currentStock: 30,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-21",
    nameEn: "Multiplex Chelated Zinc 12% (EDTA)",
    nameMr: "मल्टिप्लेक्स चिलेटेड झिंक १२% (EDTA)",
    brandId: "br-9",
    brandName: "Multiplex",
    categoryId: "cat-6",
    categoryNameEn: "Micronutrients & Secondary Nutrients",
    categoryNameMr: "सूक्ष्म अन्नद्रव्ये",
    sku: "MPX-ZN12-500G",
    hsnCode: "38089340",
    unit: "Packet",
    packSize: "500 Gm",
    mrp: 450,
    sellingPrice: 380,
    purchasePrice: 290,
    gstRate: 12,
    totalStock: 35,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Chelated Zinc (Zn-EDTA 12%)",
    targetCrops: "कांदा, मका, द्राक्ष, टोमॅटो",
    dosageGuide: "१ ग्रॅम प्रति लिटर पाणी फवारणीसाठी",
    descriptionEn: "100% water soluble chelated zinc for rapid chlorophyll formation and curing yellowing.",
    descriptionMr: "पानांमधील पिवळेपणा दूर करून हरितद्रव्य वाढवणारे १००% विद्राव्य चिलेटेड झिंक.",
    batches: [
      {
        id: "batch-21a",
        productId: "prod-21",
        batchNumber: "MPX-ZN-11",
        mfgDate: "2024-04-01",
        expiryDate: "2027-03-31",
        purchaseCost: 290,
        currentStock: 35,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-22",
    nameEn: "Boron 20% (Disodium Octaborate Tetrahydrate)",
    nameMr: "बोरॉन २०% (Disodium Octaborate Tetrahydrate)",
    brandId: "br-9",
    brandName: "Multiplex",
    categoryId: "cat-6",
    categoryNameEn: "Micronutrients & Secondary Nutrients",
    categoryNameMr: "सूक्ष्म अन्नद्रव्ये",
    sku: "BORON-20-500G",
    hsnCode: "38089340",
    unit: "Packet",
    packSize: "500 Gm",
    mrp: 260,
    sellingPrice: 220,
    purchasePrice: 170,
    gstRate: 12,
    totalStock: 45,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Disodium Octaborate Tetrahydrate (Boron 20%)",
    targetCrops: "डाळिंब (फळ तडकणे प्रतिबंध), द्राक्ष, टोमॅटो, कांदा",
    dosageGuide: "१ ग्रॅम प्रति लिटर पाणी किंवा ५०० ग्रॅम प्रति एकर ठिबक",
    descriptionEn: "Essential for pollen tube growth, fruit setting, and eliminating cracking.",
    descriptionMr: "परागीभवन सुधारण्यासाठी, फळधारणा वाढवण्यासाठी व फळे तडकणे थांबवण्यासाठी.",
    batches: [
      {
        id: "batch-22a",
        productId: "prod-22",
        batchNumber: "BRN-24-10",
        mfgDate: "2024-05-02",
        expiryDate: "2027-05-01",
        purchaseCost: 170,
        currentStock: 45,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-23",
    nameEn: "Super Silicon Spreader & Sticker",
    nameMr: "सुपर सिलिकॉन स्प्रेडर व स्टीकर (फवारणी स्पेशल)",
    brandId: "br-9",
    brandName: "Multiplex",
    categoryId: "cat-7",
    categoryNameEn: "Plant Growth Regulators & Tonics",
    categoryNameMr: "टॉनिक व स्टीकर",
    sku: "SIL-STICK-250ML",
    hsnCode: "38089340",
    unit: "Bottle",
    packSize: "250 ml",
    mrp: 420,
    sellingPrice: 350,
    purchasePrice: 260,
    gstRate: 18,
    totalStock: 50,
    minStockLevel: 15,
    isAvailable: true,
    technicalName: "Organosilicone Non-Ionic Wetting & Penetrating Agent",
    targetCrops: "सर्व पिकांच्या औषध व खत फवारणीसाठी",
    dosageGuide: "०.५ मिली प्रति लिटर पाणी (५ मिली प्रति १५ लिटर पंप)",
    descriptionEn: "Maximizes spray coverage, rapid leaf penetration and prevents rain wash-off.",
    descriptionMr: "औषध पानांवर त्वरित पसरवणे, आत झिरपवणे व पावसाने औषध धुतले न जाण्यासाठी अत्यंत आवश्यक.",
    batches: [
      {
        id: "batch-23a",
        productId: "prod-23",
        batchNumber: "SIL-24-91",
        mfgDate: "2024-04-18",
        expiryDate: "2027-04-17",
        purchaseCost: 260,
        currentStock: 50,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },

  // ==========================================
  // ५. प्रमाणित बियाणे (Seeds)
  // ==========================================
  {
    id: "prod-24",
    nameEn: "Advanta Prashant Onion Seeds (Garwa)",
    nameMr: "अडव्हांटा प्रशांत कांदा बियाणे (गरवा कांदा)",
    brandId: "br-8",
    brandName: "Advanta Seeds",
    categoryId: "cat-5",
    categoryNameEn: "Seeds & Hybrids",
    categoryNameMr: "प्रमाणित बियाणे",
    sku: "ADV-ONION-500G",
    hsnCode: "12099190",
    unit: "Packet",
    packSize: "500 Gm Packet",
    mrp: 1600,
    sellingPrice: 1450,
    purchasePrice: 1180,
    gstRate: 0,
    totalStock: 50,
    minStockLevel: 15,
    isAvailable: true,
    technicalName: "Garwa Red Onion High Storage Seed",
    targetCrops: "रांगडा व उन्हाळी कांदा",
    dosageGuide: "२.५ ते ३ किलो बियाणे प्रति एकर रोपवाटिकेसाठी",
    descriptionEn: "High yield, dark red color, uniform bulb size and 6-7 months excellent storage life.",
    descriptionMr: "सिन्नर परिसरासाठी सर्वाधिक पसंतीचे ६-७ महिने उत्कृष्ट टिकवण क्षमता असणारे कांदा बियाणे.",
    batches: [
      {
        id: "batch-24a",
        productId: "prod-24",
        batchNumber: "ADV-24-S01",
        mfgDate: "2024-05-20",
        expiryDate: "2025-05-19",
        purchaseCost: 1180,
        currentStock: 50,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-25",
    nameEn: "Panchganga Super Red Onion Seeds",
    nameMr: "पंचगंगा सुपर लाल कांदा बियाणे",
    brandId: "br-15",
    brandName: "Panchganga Seeds",
    categoryId: "cat-5",
    categoryNameEn: "Seeds & Hybrids",
    categoryNameMr: "प्रमाणित बियाणे",
    sku: "PCG-ONION-500G",
    hsnCode: "12099190",
    unit: "Packet",
    packSize: "500 Gm",
    mrp: 1500,
    sellingPrice: 1350,
    purchasePrice: 1100,
    gstRate: 0,
    totalStock: 45,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Panchganga Super Red High Yielding Onion",
    targetCrops: "खरीप, लेट खरीप व रब्बी कांदा",
    dosageGuide: "२.५ ते ३ किलो प्रति एकर",
    descriptionEn: "Consistent bulb weight, shiny attractive red color, preferred by Nashik farmers.",
    descriptionMr: "नाशिक व सिन्नर भागातील शेतकऱ्यांचे विश्वासू लाल व चमकदार कांदा बियाणे.",
    batches: [
      {
        id: "batch-25a",
        productId: "prod-25",
        batchNumber: "PCG-24-01",
        mfgDate: "2024-06-01",
        expiryDate: "2025-05-31",
        purchaseCost: 1100,
        currentStock: 45,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-26",
    nameEn: "Pioneer P3396 Hybrid Maize Seeds",
    nameMr: "पायोनिअर P3396 हायब्रिड मका बियाणे",
    brandId: "br-16",
    brandName: "Pioneer Seeds",
    categoryId: "cat-5",
    categoryNameEn: "Seeds & Hybrids",
    categoryNameMr: "प्रमाणित बियाणे",
    sku: "PIO-MAIZE-4KG",
    hsnCode: "12099190",
    unit: "Bag",
    packSize: "4 Kg Bag",
    mrp: 1420,
    sellingPrice: 1280,
    purchasePrice: 1040,
    gstRate: 0,
    totalStock: 35,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Pioneer P3396 High Yielding Yellow Maize Hybrid",
    targetCrops: "खरीप व रब्बी मका",
    dosageGuide: "७-८ किलो बियाणे प्रति एकर",
    descriptionEn: "Heavy grain weight, deep orange kernels, drought tolerant and high yielding.",
    descriptionMr: "सिन्नर तालुक्यातील कोरडवाहू व बागायती मका उत्पादकांसाठी भरघोस उत्पादनाचे बियाणे.",
    batches: [
      {
        id: "batch-26a",
        productId: "prod-26",
        batchNumber: "PIO-3396-8",
        mfgDate: "2024-05-15",
        expiryDate: "2025-05-14",
        purchaseCost: 1040,
        currentStock: 35,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-27",
    nameEn: "Syngenta Abhinav Hybrid Tomato Seeds",
    nameMr: "सिंजेन्टा अभिनव हायब्रिड टोमॅटो बियाणे",
    brandId: "br-4",
    brandName: "Syngenta India",
    categoryId: "cat-5",
    categoryNameEn: "Seeds & Hybrids",
    categoryNameMr: "प्रमाणित बियाणे",
    sku: "SYN-ABH-10G",
    hsnCode: "12099190",
    unit: "Packet",
    packSize: "10 Gm Packet",
    mrp: 950,
    sellingPrice: 850,
    purchasePrice: 690,
    gstRate: 0,
    totalStock: 40,
    minStockLevel: 10,
    isAvailable: true,
    technicalName: "Abhinav F1 Hybrid Tomato",
    targetCrops: "टोमॅटो लागवड",
    dosageGuide: "४०-५० ग्रॅम बियाणे प्रति एकर रोपवाटिकेसाठी",
    descriptionEn: "Firm, square-round fruits, excellent transportation tolerance and high disease resistance.",
    descriptionMr: "लांबच्या वाहतुकीसाठी उत्कृष्ट कडक फळे व रोगप्रतिकारक लोकप्रिय टोमॅटो बियाणे.",
    batches: [
      {
        id: "batch-27a",
        productId: "prod-27",
        batchNumber: "SYN-ABH-99",
        mfgDate: "2024-04-10",
        expiryDate: "2025-04-09",
        purchaseCost: 690,
        currentStock: 40,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },

  // ==========================================
  // ६. तणनाशके (Herbicides)
  // ==========================================
  {
    id: "prod-28",
    nameEn: "Dhanuka Targa Super Herbicide",
    nameMr: "धनुका टरगा सुपर तणनाशक (Quizalofop-Ethyl)",
    brandId: "br-6",
    brandName: "Dhanuka Agritech",
    categoryId: "cat-8",
    categoryNameEn: "Herbicides & Weedicides",
    categoryNameMr: "तणनाशके",
    sku: "DHN-TRG-250ML",
    hsnCode: "38089390",
    unit: "Bottle",
    packSize: "250 ml",
    mrp: 460,
    sellingPrice: 395,
    purchasePrice: 310,
    gstRate: 18,
    totalStock: 30,
    minStockLevel: 8,
    isAvailable: true,
    technicalName: "Quizalofop Ethyl 5% EC",
    targetCrops: "कांदा, सोयाबीन, भुईमूग, कापूस (अरुंद पानांचे गवत)",
    dosageGuide: "२ मिली प्रति लिटर पाणी (३००-४०० मिली प्रति एकर)",
    descriptionEn: "Selective post-emergence herbicide for controlling narrow-leaf grassy weeds without harming broadleaf crops.",
    descriptionMr: "कांदा व सोयाबीन पिकाला इजा न पोहचवता अरुंद पानांच्या गवताचे समूळ नियंत्रण करणारे तणनाशक.",
    batches: [
      {
        id: "batch-28a",
        productId: "prod-28",
        batchNumber: "TRG-24-10",
        mfgDate: "2024-05-01",
        expiryDate: "2027-04-30",
        purchaseCost: 310,
        currentStock: 30,
        isDemo: true,
      },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
];`;

const startIndex = content.indexOf('export const INITIAL_BRANDS');
const endIndex = content.indexOf('export const INITIAL_CUSTOMERS');

if (startIndex !== -1 && endIndex !== -1) {
  content = content.substring(0, startIndex) + brandsAndProducts + '\n\n' + content.substring(endIndex);
  fs.writeFileSync(storePath, content, 'utf8');
  console.log('✅ store.ts successfully updated with 28 rich agricultural products and brands!');
} else {
  console.error('❌ Could not find replacement boundaries in store.ts');
}
